# Generated by Django 5.2.2 on 2025-10-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('category', models.CharField(choices=[('packers', 'Пакеры'), ('anchors', 'Якоря'), ('assemblies', 'Компоновки'), ('parts', 'Запчасти')], max_length=20, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('diameter', models.CharField(blank=True, max_length=50, verbose_name='Диаметр')),
                ('working_pressure', models.CharField(blank=True, max_length=100, verbose_name='Рабочее давление')),
                ('temperature', models.CharField(blank=True, max_length=100, verbose_name='Температура')),
                ('load_capacity', models.CharField(blank=True, max_length=100, verbose_name='Нагрузка')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Материал')),
                ('length', models.CharField(blank=True, max_length=100, verbose_name='Длина')),
                ('weight', models.CharField(blank=True, max_length=100, verbose_name='Вес')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
    ]
