# Generated by Django 5.2.2 on 2025-10-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='diameter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='load_capacity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='working_pressure',
        ),
        migrations.AddField(
            model_name='product',
            name='application',
            field=models.TextField(blank=True, verbose_name='Область применения'),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, verbose_name='Отличительные особенности и преимущества'),
        ),
    ]
