# Generated by Django 5.2.2 on 2025-10-15 19:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_product_diameter_remove_product_length_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name_ru'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='application',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='product',
            name='application_az',
            field=models.TextField(blank=True, null=True, verbose_name='Область применения (азерб.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='application_en',
            field=models.TextField(blank=True, null=True, verbose_name='Область применения (англ.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='application_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Область применения (рус.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_az',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (азерб.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (англ.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Описание (рус.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='features_az',
            field=models.TextField(blank=True, null=True, verbose_name='Особенности (азерб.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='features_en',
            field=models.TextField(blank=True, null=True, verbose_name='Особенности (англ.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='features_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Особенности (рус.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_az',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название (азерб.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название (англ.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Название (рус.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_az',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Краткое описание (азерб.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Краткое описание (англ.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_ru',
            field=models.TextField(default=django.utils.timezone.now, max_length=500, verbose_name='Краткое описание (рус.)'),
            preserve_default=False,
        ),
    ]
