# Generated by Django 5.2.2 on 2025-10-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_options_remove_product_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('packers', 'Пакеры'), ('anchors', 'Якоря'), ('packer assemblies', 'Пакерные компоновки'), ('valves and well chambers', 'Клапаны и скважинные камеры'), ('disconnectors and others', 'Разъединители и другое')], max_length=32, verbose_name='Категория'),
        ),
    ]
